"""PromptWitness public API."""

from .adapters import (
    AdapterError,
    AdapterFormat,
    AdapterResult,
    adapt_prompt,
    load_adapted_prompt,
    prompt_to_dict,
    render_prompt_json,
)
from .benchmark import (
    SCORERS,
    BenchmarkCase,
    BenchmarkGate,
    BenchmarkReport,
    BenchmarkResult,
    BenchmarkSuite,
    BenchmarkTask,
    evaluate_benchmark,
    load_benchmark_cases,
    load_benchmark_suite,
    score_prediction,
)
from .diff import DiffOptions, MessageAlignment, compare_prompts
from .execution import ExecutionReport, ExecutionRow, ScenarioExecutor
from .invocations import ToolArgumentIssue, ToolArgumentReport, validate_tool_arguments
from .long_context import (
    LongContextCase,
    LongContextReport,
    LongContextResult,
    evaluate_long_context,
    make_needle_cases,
    make_provider_answerer,
)
from .matrix import (
    MatrixArtifact,
    MatrixDiff,
    RenderedScenario,
    Scenario,
    compare_matrices,
    render_matrix,
    save_matrix,
)
from .models import (
    Change,
    ChangeKind,
    ContentBlock,
    DiffReport,
    Finding,
    FindingCode,
    Message,
    PromptDocument,
    Severity,
    ToolSpec,
    ValidationReport,
)
from .parser import PromptFormatError, load_prompt, parse_prompt
from .policies import PolicyBundle, PolicyFormatError, load_policy, parse_policy
from .provider_matrix import (
    ProviderMatrix,
    ProviderMatrixReport,
    ProviderRun,
    ProviderSpec,
    load_replay_providers,
)
from .providers import (
    OpenAICompatibleProvider,
    OpenAICompatibleStreamingProvider,
    ProviderTrace,
    ReplayProvider,
    TraceEvent,
    TraceRecorder,
    load_traces,
)
from .registry import PromptRegistry, PromptVersion, RenderedPrompt
from .schemas import resolve_local_refs
from .service import PromptService, create_server
from .sessions import (
    OpenAISessionProvider,
    SessionConflict,
    SessionEvent,
    SessionJournal,
    SessionReplayProvider,
    SessionRequest,
    SessionRunner,
    SessionTransitionError,
    SessionView,
    replay_session,
)
from .tools import ToolBatch, ToolDispatcher, ToolOutcome
from .validation import ValidationPolicy, validate_prompt

__all__ = [
    "SCORERS",
    "AdapterError",
    "AdapterFormat",
    "AdapterResult",
    "BenchmarkCase",
    "BenchmarkGate",
    "BenchmarkReport",
    "BenchmarkResult",
    "BenchmarkSuite",
    "BenchmarkTask",
    "Change",
    "ChangeKind",
    "ContentBlock",
    "DiffOptions",
    "DiffReport",
    "ExecutionReport",
    "ExecutionRow",
    "Finding",
    "FindingCode",
    "LongContextCase",
    "LongContextReport",
    "LongContextResult",
    "MatrixArtifact",
    "MatrixDiff",
    "Message",
    "MessageAlignment",
    "OpenAICompatibleProvider",
    "OpenAICompatibleStreamingProvider",
    "OpenAISessionProvider",
    "PolicyBundle",
    "PolicyFormatError",
    "PromptDocument",
    "PromptFormatError",
    "PromptRegistry",
    "PromptService",
    "PromptVersion",
    "ProviderMatrix",
    "ProviderMatrixReport",
    "ProviderRun",
    "ProviderSpec",
    "ProviderTrace",
    "RenderedPrompt",
    "RenderedScenario",
    "ReplayProvider",
    "Scenario",
    "ScenarioExecutor",
    "SessionConflict",
    "SessionEvent",
    "SessionJournal",
    "SessionReplayProvider",
    "SessionRequest",
    "SessionRunner",
    "SessionTransitionError",
    "SessionView",
    "Severity",
    "ToolArgumentIssue",
    "ToolArgumentReport",
    "ToolBatch",
    "ToolDispatcher",
    "ToolOutcome",
    "ToolSpec",
    "TraceEvent",
    "TraceRecorder",
    "ValidationPolicy",
    "ValidationReport",
    "adapt_prompt",
    "compare_matrices",
    "compare_prompts",
    "create_server",
    "evaluate_benchmark",
    "evaluate_long_context",
    "load_adapted_prompt",
    "load_benchmark_cases",
    "load_benchmark_suite",
    "load_policy",
    "load_prompt",
    "load_replay_providers",
    "load_traces",
    "make_needle_cases",
    "make_provider_answerer",
    "parse_policy",
    "parse_prompt",
    "prompt_to_dict",
    "render_matrix",
    "render_prompt_json",
    "replay_session",
    "resolve_local_refs",
    "save_matrix",
    "score_prediction",
    "validate_prompt",
    "validate_tool_arguments",
]

__version__ = "0.2.0"
