"""PromptWitness public API."""

from .adapters import (
    AdapterError,
    AdapterFormat,
    AdapterResult,
    adapt_prompt,
    load_adapted_prompt,
    prompt_to_dict,
    render_prompt_json,
)
from .benchmark import (
    SCORERS,
    BenchmarkCase,
    BenchmarkGate,
    BenchmarkReport,
    BenchmarkResult,
    BenchmarkSuite,
    BenchmarkTask,
    evaluate_benchmark,
    load_benchmark_cases,
    load_benchmark_suite,
    score_prediction,
)
from .diff import DiffOptions, MessageAlignment, compare_prompts
from .execution import ExecutionReport, ExecutionRow, ScenarioExecutor
from .interview_journal import (
    InterviewJournal,
    InterviewJournalConflict,
    InterviewJournalError,
    InterviewNotFoundError,
    InterviewReceipt,
    verify_interview_export,
)
from .interview_memory import BM25MemoryIndex, MemoryEntry, MemorySnapshot, SourceHead
from .interview_models import (
    BoundEvidence,
    CriterionAssessment,
    CriterionLink,
    EvidenceRef,
    InterviewBudgets,
    InterviewContractError,
    InterviewCriterion,
    InterviewPlan,
    InterviewTopic,
    MemoryRecord,
    ParticipantAnswer,
    RetrievalPolicy,
    assessed_coverage,
)
from .interview_state import InterviewCommand, InterviewEvent, InterviewState, interview_report
from .interviews import InterviewRunner, OpenAIInterviewProvider, create_interview
from .invocations import ToolArgumentIssue, ToolArgumentReport, validate_tool_arguments
from .long_context import (
    LongContextCase,
    LongContextReport,
    LongContextResult,
    evaluate_long_context,
    make_needle_cases,
    make_provider_answerer,
)
from .matrix import (
    MatrixArtifact,
    MatrixDiff,
    RenderedScenario,
    Scenario,
    compare_matrices,
    render_matrix,
    save_matrix,
)
from .models import (
    Change,
    ChangeKind,
    ContentBlock,
    DiffReport,
    Finding,
    FindingCode,
    Message,
    PromptDocument,
    Severity,
    ToolSpec,
    ValidationReport,
)
from .parser import PromptFormatError, load_prompt, parse_prompt
from .policies import PolicyBundle, PolicyFormatError, load_policy, parse_policy
from .procedure_baselines import (
    ProcedureBaselineLimits,
    ProcedureBaselineResult,
    solve_countdown,
    walk_graph_path,
)
from .procedure_data import (
    ProcedureCase,
    ProcedureDataLimits,
    ProcedureDataset,
    audit_longproc_data,
    load_longproc_dataset,
    normalize_longproc_record,
)
from .procedure_json_data import ProcedureDataError
from .procedure_plan import (
    ProcedurePlanLimits,
    ProcedureSuitePlan,
    build_procedure_plan,
    load_procedure_suite,
    procedure_messages,
)
from .procedure_scores import ProcedureScoreLimitError, ProcedureScoreLimits, score_procedure
from .provider_matrix import (
    ProviderMatrix,
    ProviderMatrixReport,
    ProviderRun,
    ProviderSpec,
    load_replay_providers,
)
from .providers import (
    OpenAICompatibleProvider,
    OpenAICompatibleStreamingProvider,
    ProviderTrace,
    ReplayProvider,
    TraceEvent,
    TraceRecorder,
    load_traces,
)
from .registry import PromptRegistry, PromptVersion, RenderedPrompt
from .schemas import resolve_local_refs
from .service import PromptService, create_server
from .sessions import (
    OpenAISessionProvider,
    SessionConflict,
    SessionEvent,
    SessionJournal,
    SessionReplayProvider,
    SessionRequest,
    SessionRunner,
    SessionTransitionError,
    SessionView,
    replay_session,
)
from .task_data import FAMILIES, TaskSuitePlan, load_task_suite
from .task_runs import OpenAITaskProvider, TaskRequest, TaskRunConflict, TaskRunStore
from .task_scores import score_task
from .tools import ToolBatch, ToolDispatcher, ToolOutcome
from .validation import ValidationPolicy, validate_prompt

__all__ = [
    "FAMILIES",
    "SCORERS",
    "AdapterError",
    "AdapterFormat",
    "AdapterResult",
    "BM25MemoryIndex",
    "BenchmarkCase",
    "BenchmarkGate",
    "BenchmarkReport",
    "BenchmarkResult",
    "BenchmarkSuite",
    "BenchmarkTask",
    "BoundEvidence",
    "Change",
    "ChangeKind",
    "ContentBlock",
    "CriterionAssessment",
    "CriterionLink",
    "DiffOptions",
    "DiffReport",
    "EvidenceRef",
    "ExecutionReport",
    "ExecutionRow",
    "Finding",
    "FindingCode",
    "InterviewBudgets",
    "InterviewCommand",
    "InterviewContractError",
    "InterviewCriterion",
    "InterviewEvent",
    "InterviewJournal",
    "InterviewJournalConflict",
    "InterviewJournalError",
    "InterviewNotFoundError",
    "InterviewPlan",
    "InterviewReceipt",
    "InterviewRunner",
    "InterviewState",
    "InterviewTopic",
    "LongContextCase",
    "LongContextReport",
    "LongContextResult",
    "MatrixArtifact",
    "MatrixDiff",
    "MemoryEntry",
    "MemoryRecord",
    "MemorySnapshot",
    "Message",
    "MessageAlignment",
    "OpenAICompatibleProvider",
    "OpenAICompatibleStreamingProvider",
    "OpenAIInterviewProvider",
    "OpenAISessionProvider",
    "OpenAITaskProvider",
    "ParticipantAnswer",
    "PolicyBundle",
    "PolicyFormatError",
    "ProcedureBaselineLimits",
    "ProcedureBaselineResult",
    "ProcedureCase",
    "ProcedureDataError",
    "ProcedureDataLimits",
    "ProcedureDataset",
    "ProcedurePlanLimits",
    "ProcedureScoreLimitError",
    "ProcedureScoreLimits",
    "ProcedureSuitePlan",
    "PromptDocument",
    "PromptFormatError",
    "PromptRegistry",
    "PromptService",
    "PromptVersion",
    "ProviderMatrix",
    "ProviderMatrixReport",
    "ProviderRun",
    "ProviderSpec",
    "ProviderTrace",
    "RenderedPrompt",
    "RenderedScenario",
    "ReplayProvider",
    "RetrievalPolicy",
    "Scenario",
    "ScenarioExecutor",
    "SessionConflict",
    "SessionEvent",
    "SessionJournal",
    "SessionReplayProvider",
    "SessionRequest",
    "SessionRunner",
    "SessionTransitionError",
    "SessionView",
    "Severity",
    "SourceHead",
    "TaskRequest",
    "TaskRunConflict",
    "TaskRunStore",
    "TaskSuitePlan",
    "ToolArgumentIssue",
    "ToolArgumentReport",
    "ToolBatch",
    "ToolDispatcher",
    "ToolOutcome",
    "ToolSpec",
    "TraceEvent",
    "TraceRecorder",
    "ValidationPolicy",
    "ValidationReport",
    "adapt_prompt",
    "assessed_coverage",
    "audit_longproc_data",
    "build_procedure_plan",
    "compare_matrices",
    "compare_prompts",
    "create_interview",
    "create_server",
    "evaluate_benchmark",
    "evaluate_long_context",
    "interview_report",
    "load_adapted_prompt",
    "load_benchmark_cases",
    "load_benchmark_suite",
    "load_longproc_dataset",
    "load_policy",
    "load_procedure_suite",
    "load_prompt",
    "load_replay_providers",
    "load_task_suite",
    "load_traces",
    "make_needle_cases",
    "make_provider_answerer",
    "normalize_longproc_record",
    "parse_policy",
    "parse_prompt",
    "procedure_messages",
    "prompt_to_dict",
    "render_matrix",
    "render_prompt_json",
    "replay_session",
    "resolve_local_refs",
    "save_matrix",
    "score_prediction",
    "score_procedure",
    "score_task",
    "solve_countdown",
    "validate_prompt",
    "validate_tool_arguments",
    "verify_interview_export",
    "walk_graph_path",
]

__version__ = "0.2.0"
