"""Machine-readable, Markdown, and standalone HTML reports."""

from __future__ import annotations

import json
import re
from collections.abc import Mapping
from html import escape
from typing import Any

from .models import Change, DiffReport, Finding, ValidationReport

REPORT_SCHEMA_VERSION = 1


def diff_to_dict(report: DiffReport) -> dict[str, Any]:
    """Convert a diff report to the stable versioned wire shape."""

    return {
        "schema_version": REPORT_SCHEMA_VERSION,
        "report_type": "diff",
        "before_id": report.before_id,
        "after_id": report.after_id,
        "compatible": report.compatible,
        "summary": {
            "changes": len(report.changes),
            "breaking": report.breaking_count,
            "warnings": report.warning_count,
        },
        "changes": [_change_to_dict(change) for change in report.changes],
    }


def validation_to_dict(report: ValidationReport) -> dict[str, Any]:
    """Convert a validation report to the stable versioned wire shape."""

    return {
        "schema_version": REPORT_SCHEMA_VERSION,
        "report_type": "validation",
        "prompt_id": report.prompt_id,
        "valid": report.valid,
        "summary": {
            "findings": len(report.findings),
            "breaking": report.breaking_count,
            "warnings": report.warning_count,
        },
        "findings": [_finding_to_dict(finding) for finding in report.findings],
    }


def render_json(report: DiffReport | ValidationReport) -> str:
    """Render a report as deterministic UTF-8-friendly JSON."""

    payload = diff_to_dict(report) if isinstance(report, DiffReport) else validation_to_dict(report)
    return json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True, allow_nan=False) + "\n"


def render_markdown(report: DiffReport | ValidationReport) -> str:
    """Render a compact human review document."""

    if isinstance(report, DiffReport):
        return _render_diff_markdown(report)
    return _render_validation_markdown(report)


def render_html(report: DiffReport | ValidationReport) -> str:
    """Render a self-contained HTML report with no network dependencies."""

    title, subtitle, status_class, status_text, rows = _html_content(report)
    body_rows = "\n".join(rows) or '<tr><td colspan="4" class="empty">No findings</td></tr>'
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(title)}</title>
<style>
:root {{ color-scheme: light dark; --bg:#f5f7fb; --card:#fff; --ink:#172033;
  --muted:#61708a; --line:#dce2ec; --info:#2563eb; --warning:#b45309; --breaking:#b91c1c; }}
@media (prefers-color-scheme: dark) {{ :root {{ --bg:#101521; --card:#171e2d; --ink:#edf2ff;
  --muted:#aab6cb; --line:#303b50; --info:#79a7ff; --warning:#ffc266; --breaking:#ff8d8d; }} }}
* {{ box-sizing:border-box }} body {{ margin:0; background:var(--bg); color:var(--ink);
  font:15px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif }}
main {{ max-width:1240px; margin:48px auto; padding:0 24px }}
header {{ display:flex; gap:24px; align-items:flex-start; justify-content:space-between;
  margin-bottom:22px }}
h1 {{ margin:0 0 5px; font-size:30px }} p {{ margin:0; color:var(--muted) }}
.badge {{ border:1px solid currentColor; border-radius:999px; padding:7px 12px; font-weight:700 }}
.pass {{ color:#16803c }} .fail {{ color:var(--breaking) }}
.card {{ background:var(--card); border:1px solid var(--line); border-radius:12px; overflow:hidden;
  box-shadow:0 10px 26px rgba(30,45,75,.08) }}
table {{ width:100%; border-collapse:collapse }} th,td {{ padding:13px 15px; text-align:left;
  vertical-align:top; border-bottom:1px solid var(--line) }}
th {{ color:var(--muted); font-size:12px;
  text-transform:uppercase; letter-spacing:.055em }} tr:last-child td {{ border-bottom:0 }}
th:nth-child(1) {{ width:10% }} th:nth-child(2) {{ width:22% }}
th:nth-child(3) {{ width:38% }} th:nth-child(4) {{ width:30% }}
code {{ font:13px ui-monospace,SFMono-Regular,Consolas,monospace; overflow-wrap:anywhere }}
td:nth-child(1),td:nth-child(2) {{ white-space:nowrap }}
.severity {{ font-weight:700 }} .severity.info {{ color:var(--info) }}
.severity.warning {{ color:var(--warning) }} .severity.breaking {{ color:var(--breaking) }}
.empty {{ color:var(--muted); text-align:center; padding:32px }}
footer {{ margin-top:14px; color:var(--muted) }}
</style>
</head>
<body>
<main>
<header><div><h1>{escape(title)}</h1><p>{escape(subtitle)}</p></div>
<span class="badge {status_class}">{escape(status_text)}</span></header>
<div class="card"><table><thead><tr>
<th>Severity</th><th>Kind</th><th>Path</th><th>Summary</th>
</tr></thead>
<tbody>{body_rows}</tbody></table></div>
<footer>Generated by PromptWitness · report schema {REPORT_SCHEMA_VERSION}</footer>
</main></body></html>
"""


def _change_to_dict(change: Change) -> dict[str, Any]:
    return {
        "kind": change.kind.value,
        "path": change.path,
        "severity": change.severity.value,
        "summary": change.summary,
        "before": _json_value(change.before),
        "after": _json_value(change.after),
        "unified_diff": list(change.unified_diff),
    }


def _finding_to_dict(finding: Finding) -> dict[str, str]:
    return {
        "code": finding.code.value,
        "path": finding.path,
        "severity": finding.severity.value,
        "message": finding.message,
    }


def _render_diff_markdown(report: DiffReport) -> str:
    state = "compatible" if report.compatible else "breaking"
    lines = [
        "# PromptWitness diff",
        "",
        f"`{_md(report.before_id)}` → `{_md(report.after_id)}` · **{state}** · "
        f"{len(report.changes)} change(s), {report.breaking_count} breaking",
        "",
        "| Severity | Kind | Path | Summary |",
        "|---|---|---|---|",
    ]
    for change in report.changes:
        lines.append(
            f"| {change.severity.value} | `{change.kind.value}` | `{_md(change.path)}` | "
            f"{_md(change.summary)} |"
        )
    if not report.changes:
        lines.append("| — | — | — | No changes |")
    diffs = [change for change in report.changes if change.unified_diff]
    for change in diffs:
        fence = _markdown_fence(change.unified_diff)
        lines.extend(
            [
                "",
                f"## `{_md(change.path)}`",
                "",
                f"{fence}diff",
                *change.unified_diff,
                fence,
            ]
        )
    return "\n".join(lines) + "\n"


def _render_validation_markdown(report: ValidationReport) -> str:
    state = "valid" if report.valid else "invalid"
    lines = [
        "# PromptWitness validation",
        "",
        f"`{_md(report.prompt_id)}` · **{state}** · {len(report.findings)} finding(s), "
        f"{report.breaking_count} breaking",
        "",
        "| Severity | Code | Path | Message |",
        "|---|---|---|---|",
    ]
    for finding in report.findings:
        lines.append(
            f"| {finding.severity.value} | `{finding.code.value}` | `{_md(finding.path)}` | "
            f"{_md(finding.message)} |"
        )
    if not report.findings:
        lines.append("| — | — | — | No findings |")
    return "\n".join(lines) + "\n"


def _html_content(
    report: DiffReport | ValidationReport,
) -> tuple[str, str, str, str, list[str]]:
    rows: list[str] = []
    if isinstance(report, DiffReport):
        title = "PromptWitness diff"
        subtitle = (
            f"{report.before_id} → {report.after_id} · {len(report.changes)} change(s) · "
            f"{report.breaking_count} breaking"
        )
        status_class, status_text = (
            ("pass", "Compatible") if report.compatible else ("fail", "Breaking changes")
        )
        for change in report.changes:
            rows.append(
                _html_row(
                    change.severity.value,
                    change.kind.value,
                    change.path,
                    change.summary,
                )
            )
    else:
        title = "PromptWitness validation"
        subtitle = (
            f"{report.prompt_id} · {len(report.findings)} finding(s) · "
            f"{report.breaking_count} breaking"
        )
        status_class, status_text = ("pass", "Valid") if report.valid else ("fail", "Invalid")
        for finding in report.findings:
            rows.append(
                _html_row(
                    finding.severity.value,
                    finding.code.value,
                    finding.path,
                    finding.message,
                )
            )
    return title, subtitle, status_class, status_text, rows


def _html_row(severity: str, kind: str, path: str, summary: str) -> str:
    return (
        f'<tr><td><span class="severity {severity}">{escape(severity)}</span></td>'
        f"<td><code>{escape(kind)}</code></td><td><code>{escape(path)}</code></td>"
        f"<td>{escape(summary)}</td></tr>"
    )


def _md(value: str) -> str:
    return (
        value.replace("&", "&amp;")
        .replace("|", "&#124;")
        .replace("`", "&#96;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\r", " ")
        .replace("\n", " ")
    )


def _markdown_fence(lines: tuple[str, ...]) -> str:
    longest = 0
    for line in lines:
        longest = max(longest, *(len(match) for match in re.findall(r"`+", line)), 0)
    return "`" * max(3, longest + 1)


def _json_value(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {key: _json_value(nested) for key, nested in value.items()}
    if isinstance(value, tuple):
        return [_json_value(item) for item in value]
    return value
